Fix release crash
Introduced in cdddbbc9c0dc277d8ecd8b24e8603d43870a3739, with the exclusion of the Gemfile.

```
+ rake release
Running gem release task...
rake aborted!
Gem::MissingSpecError: Could not find 'public_suffix' (>= 2.0.2, < 8.0) among 118 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/github/home/.gem/ruby/3.4.0:/usr/local/lib/ruby/gems/3.4.0:/usr/local/bundle' at: /usr/local/bundle/specifications/addressable-2.8.9.gemspec, execute `gem env` for more information
<internal:/usr/local/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:139:in 'block in Kernel#require'
<internal:/usr/local/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:139:in 'Monitor#synchronize'
<internal:/usr/local/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:139:in 'Kernel#require'
/github/workspace/Rakefile:18:in '<top (required)>'
/usr/local/bundle/gems/rake-13.3.1/exe/rake:27:in '<top (required)>'

Caused by:
Gem::MissingSpecError: Could not find 'public_suffix' (>= 2.0.2, < 8.0) among 118 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/github/home/.gem/ruby/3.4.0:/usr/local/lib/ruby/gems/3.4.0:/usr/local/bundle' at: /usr/local/bundle/specifications/addressable-2.8.9.gemspec, execute `gem env` for more information
<internal:/usr/local/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:139:in 'block in Kernel#require'
<internal:/usr/local/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:139:in 'Monitor#synchronize'
<internal:/usr/local/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:139:in 'Kernel#require'
/github/workspace/Rakefile:18:in '<top (required)>'
/usr/local/bundle/gems/rake-13.3.1/exe/rake:27:in '<top (required)>'

Caused by:
LoadError: cannot load such file -- rubocop/rake_task (LoadError)
<internal:/usr/local/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
<internal:/usr/local/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
/github/workspace/Rakefile:18:in '<top (required)>'
/usr/local/bundle/gems/rake-13.3.1/exe/rake:27:in '<top (required)>'
(See full trace by running task with --trace)
```